### ISSUE TITLE
Theme matching

### ISSUE THREAD

**Issue by downhamdave** [dokufreaks/plugin-linkback#11]
I am not sure if it is a problem that stems from the theme I use (bootstrap3), but the  Linkback box doesn't really match the thematic formatting... whereas, for instance, the Discussion plugin adapts.

**Comment by LarsGit223** [comment]
I compared the CSS code from the linkback and discussion plugin. They CSS code looks quite similar, I did not find a reason for the different theme matching in bootstrap3.

If I use the DokuWiki standard theme linkback and discussion have the same layout/colors.

**Comment by Klap-in** [comment]
Maybe you could add a picture to explain the case for peoples that have not (yet) installed the templates?

**Comment by michitux** [comment]
Maybe the template has special code for the discussion plugin?

**Comment by LarsGit223** [comment]
This is how linkback and discussion look on my PC:

First with the DokuWiki standard template:

![linkbackdiscussion_dokuwikitemplate](https://cloud.githubusercontent.com/assets/9009011/15868710/4a5ff30a-2ce9-11e6-884c-5b8c5666f649.png)

And two screenshots (it did not fit on one page) from the bootstrap3 template:

From the top:
![linkbackdiscussion_bootstrap3template_top](https://cloud.githubusercontent.com/assets/9009011/15868753/771154de-2ce9-11e6-8c3d-8a9e1fb92512.png)

From the bottom:
![linkbackdiscussion_bootstrap3template_buttom](https://cloud.githubusercontent.com/assets/9009011/15868756/7ba04190-2ce9-11e6-9d64-7c488afb4ea9.png)

**Comment by LarsGit223** [comment]
I noticed that the linkback frame is wider than all the other content.
Maybe the CSS in style.css should be changed from

```
div.dokuwiki div.linkback_wrapper {
  background-color: __background_alt__;
  margin: 1em -1em;
  padding: 0.5em 1em;
  clear: both;
}
```
to
```
div.dokuwiki div.linkback_wrapper {
  background-color: __background_alt__;
  margin: 1em 0em;
  padding: 0.5em 1em;
  clear: both;
}
```
Just a suggestion, has nothing to do with the different colors.

**Comment by LarsGit223** [comment]
I checked the template code. There is extra css/less and JavaScript code for the discussion and other plugins, see also https://www.dokuwiki.org/template:bootstrap3#plugin_integration.

It looks like the .less code is e.g. changing the background-color to **inherit**.

So it really seems to be a template issue. I suggest to open a new issue in the bootstrap3 issues section. This should be closed I think. Any remarks?

**Comment by downhamdave** [comment]
Thanks, I think the colour thing may be related to the Bootstrap3 theme, where in many of the colour options the "template style settings" colours don't match the themes. Though I guess the colours like background_alt part of Dokuwiki is rather entrenched in the code!

The CSS amendment suggested to the styles.css helps. I also removed 
background-color: __background_alt__;

**Comment by LarsGit223** [comment]
Ok, I saw you opened the issue in the bootstrap3 template so I will close this.
